---

- hosts: glusterfs_server
  remote_user: vagrant
  become: yes
  roles:
    - glusterfs/server
  tags: server

- hosts: glusterfs_client
  remote_user: vagrant
  become: yes
  roles:
    - glusterfs/client
  tags: client
