---

###
# GLUSTERFS
###

glusterfs_storage_dir: /mnt

glusterfs_volumes:
  - src: "{{ hostvars[groups['glusterfs_server'][0]].ip }}:/data1"
    dest: "{{ glusterfs_storage_dir }}/data1"
    options: defaults,_netdev
    owner: root
    group: root
    mode: "0755"
  - src: "{{ hostvars[groups['glusterfs_server'][0]].ip }}:/data2"
    dest: "{{ glusterfs_storage_dir }}/data2"
    options: defaults,_netdev
    owner: root
    group: root
    mode: "0755"
